spring:
  application:
    name: dear-comrade-jpa-hibernate-zero-to-hero
  datasource:
    url: jdbc:postgresql://172.21.0.2:5432/dha
    username: comrade
    password: dear
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

