spring:
  application:
    name: dear-comrade-jpa-hibernate-zero-to-hero
  datasource:
    url: jdbc:postgresql://172.21.0.3:5432/dha
    username: comrade
    password: dear
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: "classpath:database/migration/topic-type-migration.yaml"

server:
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50
springdoc:
  swagger-ui:
    path: /swagger-ui.html

