spring:
  threads:
    virtual:
      enabled: true
  application:
    name: dear-comrade-jpa-hibernate-zero-to-hero
  datasource:
    url: jdbc:postgresql://localhost:5432/dha
    username: comrade
    password: dear
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 120000
      connection-timeout: 300000
      leak-detection-threshold: 300000
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true

server:
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50
springdoc:
  swagger-ui:
    path: /swagger-ui.html

decorator:
  datasource:
    flexy-pool:
      threshold:
        connection:
          acquire: -1
          lease: 0


